project:
  type: website
  output-dir: docs
 
website:
  title: "Sam Muir"
  favicon: images/logo_tab.png

  navbar:
    logo: images/logos.png
    title: false
    left:
      - href: index.qmd ## name of file
        text: Home ## what you want it to be called in the nav bar
      - href: about.qmd ## or if not specified it will just use the doc name in the nav bar
        text: About
      #- resources.qmd
      - href: projects.qmd 
        text: Projects & Blog
      # - href: data-viz.qmd
      #   text: Data Viz
      - href: gallery.qmd
        text: Data Viz
      
    right:
      - href: docs/CV-Web-Sam-Muir.pdf
        text: CV
      - icon: github
        href: https://github.com/shmuir
      - icon: linkedin
        href: https://www.linkedin.com/in/shmuir/
      - icon: envelope
        href: mailto:smuir@bren.ucsb.edu
      

format:
  html:
    link-external-newwindow: true
    theme: 
      light: light_styles.scss
      #dark: dark_styles.scss
    css: styles.css
    toc: true
    page-layout: full
    

editor: source
